image:
  - Visual Studio 2017

version: '1.0.{build}'

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off
  #- node make.js build --task RunOpenCover
