image:
  - Visual Studio 2017

version: '1.0.{build}'

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - gulp

build: off
  #- node make.js build --task RunOpenCover


cache:
  - node_modules -> package.json   
